version: "3.9"

services:
  perlite:
    image: sec77/perlite:latest
    container_name: perlite-build
    environment:
      - NOTES_PATH=REPOSITORIO
      - HIDE_FOLDERS=docs,private,trash
      - LINE_BREAKS=true
      - ABSOLUTE_PATHES=false
      - ALLOWED_FILE_LINK_TYPES=pdf,mp4,epub
      - DISABLE_POP_HOVER=true
      - SHOW_TOC=true
      - SHOW_LOCAL_GRAPH=true
      - HOME_FILE=Leeme
      - FONT_SIZE=20
      - HTML_SAFE_MODE=true
      - TEMP_PATH=/tmp
      - SITE_TITLE=REPOSITORIO
      - SITE_TYPE=article
      - SITE_URL=
      - SITE_IMAGE=
      - SITE_DESC=
      - SITE_NAME=
      - SITE_TWITTER=
      - SITE_LOGO=
      - SITE_HOMEPAGE=
      - SITE_GITHUB=
    volumes:
      - ./perlite:/var/www/perlite
      - ./perlite/REPOSITORIO:/var/www/perlite/REPOSITORIO:ro

  web:
    build:
        context: ./web
    image: sec77/perlite_web:stable
    container_name: perlite_web-build      
    ports:
      - 80:80 
    volumes:
      - ./perlite:/var/www/perlite
      - ./perlite/REPOSITORIO:/var/www/perlite/REPOSITORIO:ro   
    depends_on:
      - perlite

